# URL
BASE_URL=http://localhost:8000/api
BASE_URL_APP=http://localhost:5173

# DATABASE
DATABASE_URL=postgresql+asyncpg://<DB_USER>:<DB_PASSWORD>@localhost:5432/fastedgy-template

# JWT
AUTH_SECRET_KEY=<SECRET_KEY>
AUTH_ALGORITHM=HS256
AUTH_ACCESS_TOKEN_EXPIRE_MINUTES=15
AUTH_REFRESH_TOKEN_EXPIRE_DAYS=30

# DATA
DATA_PATH=.data

# API DOCS
API_DOCS=True

# LOGGER
LOG_LEVEL=info
LOG_OUTPUT=console
LOG_FORMAT=text_light
LOG_FILE=

# WORKERS
HTTP_WORKERS=1

# SMTP
SMTP_HOST=<SMTP_HOST>
SMTP_PORT=<SMTP_PORT>
SMTP_USE_TLS=True
SMTP_USERNAME=<SMTP_USERNAME>
SMTP_PASSWORD=<SMTP_PASSWORD>
SMTP_DEFAULT_FROM="FastEdgy <noreply@krafter.io>"
