[project]
name = "fastedgy-template"
description = "The template project for FastEdgy"
authors = [
    {name = "Krafter", email = "developer@krafter.io"},
]
readme = "README.md"
requires-python = ">=3.14"
dynamic = [
    "version"
]
dependencies = [
    "fastedgy",
]

[dependency-groups]
dev = [
    "pyright>=1.1.410",
    "pytest>=9.1.1",
    "pytest-xdist>=3.8.0",
    "ruff >= 0.13",
]

[tool.setuptools.packages.find]
exclude = ["web"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["B008", "B009", "RUF012"]

[tool.ruff.lint.per-file-ignores]
"server/migrations/versions/*" = ["F401", "I001"]

[tool.pytest.ini_options]
testpaths = ["server/tests"]
pythonpath = ["server"]

[tool.uv.sources]
fastedgy = { git = "https://github.com/krafterio/fastedgy" }
